apiVersion: argoproj.io/v1
kind: Application
metadata:
  name: istio-config
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/sgutierr/demorhcl.git
    targetRevision: HEAD
    path: installation/config-istio
    directory:
      include: |
        istio.yaml
        istio-cni.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  dependsOn:
    - connectivity-link-operators
