apiVersion: argoproj.io/v1
kind: Application
metadata:
  name: kuadrant-config
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/sgutierr/demorhcl.git  # Actualizar con tu repositorio
    targetRevision: HEAD
    path: installation/gateway-helm
    helm:
      valueFiles:
      - values.yaml
      parameters:
      - name: hostname
        value: "kuadrant.apps.ocp4.quitala.eu"
  destination:
    server: https://kubernetes.default.svc
    namespace: kuadrant-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  dependsOn:
    - connectivity-link-operators

